# docker/monitoring/grafana/provisioning/datasources/datasources.yml

apiVersion: 1

datasources:
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: SQLite
    uid: SQLite
    type: frser-sqlite-datasource
    access: proxy
    jsonData:
      path: /var/lib/grafana/sqlite/mydb.sqlite
