networks:

  transcendence:
    name: transcendence
    driver: bridge

services:

  gateway:
    image: nginx:1.27-alpine
    container_name: gateway
    depends_on:
      - web
      - backend
    ports:
      - "8080:80"
      - "3000:80"
      - "8443:443"
      - "4000"
    networks:
      - transcendence
    volumes:
      - ./srcs/certs:/etc/nginx/certs:ro
      - ./srcs/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/health || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 6

  web:
    build: .
    container_name: web
    volumes:
      - ./srcs/public:/app          # frontend (index.html, vite.config, etc.)
      - ./srcs/client:/app/client   # les pages TS (homePage, gamePage...)
      - ./srcs/server:/app/server   # app.ts (le router du front)
      - /app/node_modules
    env_file: .env
    networks:
      - transcendence

  backend:
    build:
      context: ./srcs/server
    container_name: backend
    volumes:
      - ./srcs/server:/app
      - ./srcs/services:/app/services # on monte le dossier services à la racine du conteneur
      - ./srcs/config:/app/config     # on monte le dossier config à la racine du conteneur
      - ./srcs/config/database/data:/app/config/database/data
      - /app/node_modules
    networks:
      - transcendence

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
    - ./srcs/config/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - transcendence
    restart: unless-stopped

    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - ./srcs/config/monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./srcs/config/monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - ./srcs/config/database/data:/var/lib/grafana/sqlite
    networks:
      - transcendence
    restart: unless-stopped
